version: '3.8'

services:
  playstation-cms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playstation_pos_enterprise_cms
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - JWT_SECRET=super_secret_jwt_key_enterprise_2026_change_in_production
      - DATABASE_URL=file:./cms.db
    volumes:
      - cms_data:/app/data

volumes:
  cms_data:
